# Generated by Django 3.2.6 on 2022-11-12 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20221112_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategories',
            name='status',
            field=models.CharField(choices=[('AC', 'Active'), ('NA', 'Not Active')], default='AC', max_length=2),
        ),
        migrations.AlterField(
            model_name='products',
            name='status',
            field=models.CharField(choices=[('AC', 'Active'), ('NA', 'Not Active')], default='AC', max_length=2),
        ),
    ]
