# Generated by Django 3.2.6 on 2022-11-12 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_productimages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimages',
            name='product',
        ),
    ]
